import type { MetadataRoute } from "next";

// Required for `output: "export"`: emitted once as /manifest.webmanifest.
export const dynamic = "force-static";

// Icons are generated by scripts/build-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "training",
    short_name: "training",
    start_url: "/dashboard/",
    display: "standalone",
    background_color: "#f7f9f7",
    theme_color: "#f7f9f7",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
